#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.
# Using the scp linux command, we're taking the following arguments:
# PATH_TO_FILE to be transferred to server,
# USER scp connects with, IP of a server, LOCATION to copy to on server
# and PATH_TO_IDENTITY_FILE for user authorization

if [ $# -lt 4 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'

	else
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
